
services:
  honeygain_landingpage:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5173:5173"
    command: >
      sh -c "npm run dev -- --host"
    mem_limit: 1524MB
    cpus: "2.25"   


